version: 2.1

orbs:
  maven: circleci/maven@0.0.12

workflows:
  maven_test:
    jobs:
      build:
          docker: # run the steps with Docker
              - image: circleci/openjdk:11-jdk-browsers-legacy

          working_directory: ~/repo
          environment:
            # Customize the JVM maximum heap limit
            MAVEN_OPTS: -Xmx3200m

          steps:
            - checkout

            # Download and cache dependencies
            - restore_cache:
                keys:
                  - v1-dependencies-{{ checksum "pom.xml" }}
                  # fallback to using the latest cache if no exact match is found
                  - v1-dependencies-

            - run: mvn install -DskipTests

            - run: mvn dependency:go-offline

            - save_cache:
                paths:
                  - ~/.m2
                key: v1-dependencies-{{ checksum "pom.xml" }}
            - run: mvn integration-test
#      - maven/test # checkout, build, test, and upload test results